version: "3.9"

services:
  express-backend:
    build: ./express-backend
    restart: always
    ports:
      - 3001:3001
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./express-backend:/usr/src/app
    command: npm start
  
  react-frontend:
    build: ./react-frontend
    restart: always
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./react-frontend:/usr/src/app
    command: npm start