version: "3.9"

services:
  api-rest:
    build: ./api-rest
    restart: always
    ports:
      - 3001:3001
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./api-rest:/usr/src/app
    command: npm start